name: Deploy to EC2
on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to Amazon ECR
        env:
          IMAGE_URI: 228041307119.dkr.ecr.ap-northeast-2.amazonaws.com/niedu-repo:${{ github.sha }}
        run: |
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 228041307119.dkr.ecr.ap-northeast-2.amazonaws.com
            
            docker stop app || true
            docker rm app || true
            
            docker pull 228041307119.dkr.ecr.ap-northeast-2.amazonaws.com/niedu-repo:${{ github.sha }}
            
            cat <<EOF > .env
            SPRING_PROFILES_ACTIVE=prod
            SPRING_DATASOURCE_URL=${{ secrets.SPRING_DATASOURCE_URL }}
            SPRING_DATASOURCE_USERNAME=${{ secrets.SPRING_DATASOURCE_USERNAME }}
            SPRING_DATASOURCE_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
            EOF
            
            docker run -d \
              --name app \
              --env-file .env \
              -p 8080:8080 \
              228041307119.dkr.ecr.ap-northeast-2.amazonaws.com/niedu-repo:${{ github.sha }}